version: '3'
services:
  app:
    build: .
    command: bash -c "rake main"
    volumes:
      - .:/myapp
      - ./tmp/bundle:/bundle
    environment:
      BUNDLE_PATH: "/bundle"
    tty: true
    stdin_open: true